lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600 # Token TTL in seconds (e.g., 1 hour)


    api_platform:
          check_path: /api/login_check
          username_path: username
          password_path: password
