controllers:
    resource: ../src/Controller/
    type: attribute


#api_get_articles:
#    path: /api/chargeArticles
#    methods: GET
#    controller: App\Controller\ApiController::chargeArticles
#api_logout:
#    path: /api/logout
#    controller: App\Controller\ApiController::logout
#    methods: [POST]

#api_login_check:
#    controller: App\Controller\ApiController::login
#    methods: POST
#    path: /api/login_check